README.md

There is/was a link to cert-manager further down in the README, but not one 
in the opening paragraph. Adding a link at the top makes it easier to understand
what cert-manager-csi (and cert-manager) are and how they work together.
```release-note
NONE
```

Add cert-manager link to beginning of README

---

cmd/app/start.go
cmd/main.go
go.mod
pkg/apis/defaults/defaults.go
pkg/apis/validation/validation.go
pkg/apis/validation/validation_test.go
pkg/filestore/writer.go
pkg/keygen/keygen.go
pkg/requestgen/generator.go
test/e2e/framework/config/config.go
test/e2e/framework/framework.go
test/e2e/framework/helper/certificaterequest.go
test/e2e/framework/helper/helper.go
test/e2e/framework/helper/kubectl.go
test/e2e/framework/helper/pod.go
test/e2e/framework/util.go
test/e2e/suite/cases/renew.go
test/e2e/suite/cases/stress.go
test/e2e/suite/cases/usages.go
test/e2e/suite/suite.go
test/e2e/suite/suite_test.go
test/e2e/util/csr.go
test/e2e/util/metadata.go

Branched from #46 
Changes the repo from `jetstack/cert-manager-csi` -> `cert-manager/csi`
```release-note
NONE
```

Repo cert manager csi

---

cmd/app/app.go

Branched from #50 
Catches context cancel so we can shutdown the driver and exit gracefully
@munnerz 
```release-note
NONE
```

Cmd ctx cancel

---

Makefile
cmd/app/app.go
cmd/app/options/options.go
deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/templates/_helpers.tpl
deploy/charts/csi-driver/templates/clusterrole.yaml
deploy/charts/csi-driver/templates/clusterrolebinding.yaml
deploy/charts/csi-driver/templates/csidriver.yaml
deploy/charts/csi-driver/templates/daemonset.yaml
deploy/charts/csi-driver/templates/serviceaccount.yaml
deploy/charts/csi-driver/values.yaml
go.mod
go.sum
test/e2e/framework/testenv.go

Branched from #52 
Adds a CLI flag for optionally using the token request token when creating CertificateRequests.
This PR will currently fail since we are testing against kube v1.16. Once more of the other PRs have landed, I will setup testing against different kube versions and we can optionally test this feature based on the kube version.
```release-note
NONE
```

Token request

---

cmd/app/app.go

I noticed while testing the storage error isn't returned properly here.
Tiny grammar nit in signRequest docstring

Actually return wrapped error, fix docstring lint

---

deploy/charts/csi-driver/templates/csidriver.yaml
deploy/example/example-app.yaml
test/run.sh

This PR allows for the CSI driver to be deployed on Kubernetes 1.22 by selectively deploying the CSIDriver at `storage.k8s.io/v1` if it is available at that version ([from Kubernetes 1.19](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#storage-resources-v122 )), else deploys it at `storage.k8s.io/v1beta1`.
I've also bumped the Kubernetes version used in e2e tests 1.16 -> 1.22.
I've tested that this works on both a 1.16 and 1.22 kind clusters

Bump storage API version v1beta1 -> v1

---

deploy/charts/csi-driver/templates/daemonset.yaml

This seems to be where the project is pushing images now. I have left
the version the same.
This repo has multi-arch image for this version which I need.
https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/eu/sig-storage%2Fcsi-node-driver-registrar@sha256:a61d309da54641db41fb8f35718f744e9f730d4d0384f8c4b186ddc9f06cbd5f/details?tab=pull
Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>

Use k8s.gcr.io repo for csi-node-driver-registrar

---

Dockerfile
Makefile
cmd/app/app.go
deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.yaml
test/run.sh

Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>
Adds support for more platform architectures.
Bumps the image version to `v0.1.1`.
Should be merged after #59 
/hold
/assign @irbekrm @jakexks

Adds support for multi-arch images, bumps version to v0.1.1

---

deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/README.md

Bumped version after #63 
After this merges, we can release a new helm chart version.
/assign @irbekrm @jakexks 
/cc @MattiasGees 
```release-note
NONE
```

Updates helm chart to v0.1.2

---

deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/templates/daemonset.yaml
deploy/charts/csi-driver/values.yaml

This allows a different hostPath to be used, working around an issue with system-tmpfiles-clean task.
Resolves https://github.com/cert-manager/csi-lib/issues/18

Move csi-data-dir configuration into values.yaml.

---

README.md

Also adds alt text for accessibility and artifacthub badge.
Spotted this pattern as part of work on https://github.com/cert-manager/istio-csr/pull/116

Fix broken HTML in README

---

deploy/example/example-app.yaml

It doesn't make much sense including this in the example, and will lead to people copy and pasting it and having a bad experience.

Remove disable-auto-renew from example Deployment

---

Makefile
deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/README.md

Spotted while reviewing deployment of chart for v0.3.0! I don't think there any reason for the `maintainers` field to vary in any chart in the cert-manager org.

Update maintainers to point at team email

---

hack/boilerplate/boilerplate.Dockerfile.txt
hack/boilerplate/boilerplate.Makefile.txt
hack/boilerplate/boilerplate.go.txt
hack/boilerplate/boilerplate.py
hack/boilerplate/boilerplate.py.txt
hack/boilerplate/boilerplate.sh.txt

Fixes the boilerplate file headers for the year 2022.
This PR correctly sets the year to `YEAR` instead of `2021` in the boilerplate header templates.
Adds the years up to 2022 for the boilerplate python script.

Fix boilerplate 2022

---

pkg/apis/v1alpha1/types.go
pkg/requestgen/generator.go
pkg/requestgen/generator_test.go
test/e2e/suite/cases/variables.go

This enables users to reference the pod's ServiceAccount name in the volumeAttributes.
An example usage would look like:
```yaml
volumeAttributes:
csi.cert-manager.io/issuer-name: ca-issuer
csi.cert-manager.io/dns-names: "${POD_NAME}.${POD_NAMESPACE}.svc.cluster.local"
csi.cert-manager.io/common-name: "${SERVICE_ACCOUNT_NAME}.${POD_NAMESPACE}"
```
This value has been provided by the Kubelet since Kubernetes 1.12, and was merged alongside the other values in kubernetes/kubernetes#67945, so the new map lookup is as safe as the existing ones.
I'll update the docs in a follow up PR
Signed-off-by: Micah Hausler <mhausler@amazon.com>

Add ServiceAccount name as a template value

---

pkg/apis/validation/validation.go
pkg/apis/validation/validation_test.go
pkg/filestore/writer_test.go

Based on the conversation [here](https://github.com/cert-manager/csi-driver/pull/103#discussion_r924488984).
This PR introduces a new filename validation function which supersedes the existing `filepathBreakout` function. This new more complete validation includes that included in the [atomic writer](https://github.com/cert-manager/csi-lib/blob/8e344a2d37de27bacb17f8e1d5ddc1f03733351a/third_party/util/atomic_writer.go#L245), as well as ensuring that the filename does not include '/'. 
Whilst most if not more validation now occurs on a filename, it also now occurs earlier in the publish volume pipeline. This is beneficial since we now expose the offending volume attribute in the error message presented to the user.

Introduce a new filename validation function

---

test/run.sh

Depends on https://github.com/cert-manager/csi-driver/pull/97 which should be merged first.
This PR upgrades the Kubernetes version to `v1.24.1` in our e2e tests.
/assign @wallrj

Upgrade Kubernetes e2e test version to v1.24.1

---

deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/templates/daemonset.yaml

Fixes #109 
See https://github.com/kubernetes-csi/node-driver-registrar/issues/21 and https://github.com/kubernetes-csi/node-driver-registrar/pull/61
/cc @munnerz 
Also updates the helm chart version ready for published release.

Remove life cycle hook from Daemonset

---

deploy/example/example-app.yaml

Signed-off-by: Sitaram IYER <sitaramkm@gmail.com>
Minor update to sample. remove the additional } from the uri-sans. Doesn't break anything.

Remove extra } from the sample uri-san

---

deploy/example/example-app.yaml
pkg/requestgen/generator.go
pkg/requestgen/generator_test.go
test/e2e/suite/cases/variables.go

Fixes #111 
PR trims the spaces of attributes which are lists. This improves UX, and enables the example given in the issue.
Updates the example deployment making use of the change.
PR also tightens validation to enforce proper URIs are passers to the URI sans attribute.

For attributes that are lists, trim space for each entry to improve UX.

---

deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/templates/daemonset.yaml
deploy/charts/csi-driver/values.yaml

In some cases, you want to use the specific sha256 digest of an image instead of a tag.
I tested this on my local setup with and without digest.

Add digest to HELM chart

---

deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.yaml

k8s.gcr.io registry is deprecated and to be shut down https://groups.google.com/a/kubernetes.io/g/dev/c/DYZYNQ_A6_c
This PR changes the registry of upstream CSI driver sidecar images to the new registry.k8s.io and also bumps to the latest minor versions of those images. I've tested that CSI driver with these images work as expected.

Use latest CSI sidecar container images from registry.k8s.io

---

deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/templates/_helpers.tpl
deploy/charts/csi-driver/templates/daemonset.yaml
deploy/charts/csi-driver/values.yaml

New values like in https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
* commonLabels
* daemonSetAnnotations
* podAnnotations
* podLabels
* affinity

Add very useful values common with the main Cert-manager chart

---

test/e2e/framework/helper/certificaterequest.go
test/e2e/framework/helper/pod.go

replace github.com/cert-manager/cert-manager/test/e2e/framework/log with github.com/cert-manager/csi-driver/test/e2e/framework/log

Fix incorrect cert-manager e2e test framework imports

---

Makefile
deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/templates/daemonset.yaml
deploy/charts/csi-driver/templates/serviceaccount.yaml
deploy/charts/csi-driver/values.yaml

This improves compatibility with helm template. This PR is based on https://github.com/cert-manager/approver-policy/pull/170
There aren't many resources defined in this chart, so there's not much to change here
This also bumps our version for a release, and bumps some k8s images we depend on. The livenessprobe image has increased by 2 minor versions here, but the [changelogs](https://github.com/kubernetes-csi/livenessprobe/tree/master/CHANGELOG) seem to indicate that the upgrades are bug fixes or CVE fixes. It seems safe to bump these in a patch release.

Add explicit namespace to namespaced resources + bump versions

---

deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.yaml

Bump the versions of the 'csi-node-driver-registrar' and 'livenessprobe' images.
Also set the version of our own image to v0.0.0 to make clear that this gets replaced before publishing.

Upgrade 'csi-node-driver-registrar' and 'livenessprobe'

---

deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.yaml
make/00_mod.mk

Part of moving everything to a common format/tool for helm docs.
Preview of the changes can be seen here:
https://github.com/ThatsMrTalbot/cert-manager-csi-driver/blob/feat/helm-tool-for-docs/deploy/charts/csi-driver/README.md
Depends on this PR being merged first https://github.com/cert-manager/csi-driver/pull/181

Use helm-tool for generating helm docs

---

cmd/app/app.go
internal/version/version.go

Prints the version info on startup and passes the version string to csi-lib.

Add version info to binary at compile time

---

deploy/charts/csi-driver/templates/csidriver.yaml

v1beta1 is no longer served as of k8s 1.22, and v1 has been available since k8s 1.19. There's no point in checking this any more; the oldest version of k8s we support with cert-manager is v1.22.

Use CSIDriver v1 unconditionally

---

deploy/charts/csi-driver/templates/daemonset.yaml

There's a [standard annotation](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-kubernetes-io-default-container) which specifies the default container for a pod with multiple containers. This changes the default container for log output when using `kubectl logs`.
I think the csi-driver container itself is a sensible default, so this PR adds that.
Tested locally with:
```console
$ cat values.yaml
podAnnotations:
example.com/annotation: hello-world
$ helm upgrade -i -n cert-manager cert-manager-csi-driver ./deploy/charts/csi-driver --set image.tag=v0.7.1 --wait --values values.yaml
$ kubectl get pods -n cert-manager cert-manager-csi-driver-qt88j -ojson | jq -r .metadata.annotations
{
"example.com/annotation": "hello-world",
"kubectl.kubernetes.io/default-container": …
```

Add default container annotation to daemonset

---

README.md

In time, we should have a central point for this kind of documentation since the process should be similar across most repos. That's tracked in https://github.com/cert-manager/makefile-modules/issues/98
For now, it's important to have at least some documentation in this repo of the process. This description is mostly copied from https://github.com/cert-manager/approver-policy/blob/135f48c7dc2137a3bae8cd71cdf2059f5843445c/README.md#release-process

Add initial documentation of release process

---

.golangci.yaml
pkg/apis/v1alpha1/types.go
test/e2e/framework/helper/kubectl.go
test/e2e/framework/testenv.go

Checked all found issues and applied fixes/ #nosec statements.
Now that all issues are fixed, I removed the gosec linter from the ignored section so future issues will be detected.

Fix gosec issues and enable gosec linter

---

deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.schema.json
deploy/charts/csi-driver/values.yaml

Similar to cert-manager and csi-driver-spiffe, set the `nodeSelector` to `kubernetes.io/os: linux` by default.

Helm: set linux nodeSelector by default

---

pkg/apis/v1alpha1/types.go
pkg/apis/validation/validation_test.go
pkg/requestgen/generator.go
pkg/requestgen/generator_test.go

Fixes #128 
This PR is a continuation of the work in #129 
I have changed the code of the `RequestForMetadata` function to use the CSV parser instead of `strings.Split` as requested in the original PR.
Would it make sense to replace the `splitList` function with `SplitWithEscapeCSV` as well? I wasn't sure if that's wanted because that code is not from #129 but was already in there before, so I left it untouched for now.
And what else needs to be done in order to get this merged?
I successfully tested it with the following manifest:
```yaml
apiVersion: "cert-manager.io/v1"
kind: "Issuer"
metadata:
name: "self-signed-issuer"
spec:
selfSigned: { }
---
apiVersion: "cert-manager.io/v1"
kind: "Certificate"
metadata:
name: "self-signed-root-cert"
spec:
secretName: "self-signed-root-cert"
isCA: …
```

Add attribute support for certificate subject

---

RELEASE.md
deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.schema.json
deploy/charts/csi-driver/values.yaml

I should've done this before v0.10.2, but ah well!

Bump other images, add note to release process about checking them

---

deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.schema.json
deploy/charts/csi-driver/values.yaml

Same as https://github.com/cert-manager/csi-driver-spiffe/pull/305
```
make generate-helm-docs generate-helm-schema
```

Bump sidecar images in preparation for release

---

OWNERS

My LGTM didn't count on https://github.com/cert-manager/csi-driver/pull/449 (example), and I want to fix this.

Updated OWNERS file to grant current c-m maintainers access
