cert-manager/csi-driver

README.md
docs/design/20190914.certificaterenewal.md

Adds design document for renewal

---

README.md

Adds 'Why CSI Driver?' section to README.md

---

deploy/cert-manager-csi-driver.yaml
deploy/example/example-app.yaml

Fix example deployment yaml

---

README.md
pkg/apis/defaults/defaults.go
pkg/apis/v1alpha1/types.go
pkg/apis/validation/validation.go
pkg/certmanager/certmanager.go
pkg/util/key.go

Write CA file is exists in CertificateRequest

---

OWNERS

Adds wallrj to OWNERS file

---

test/run.sh

This will help debugging both #39 and #40 :)
/cc @JoshVanL 
Signed-off-by: James Munnelly <jmunnelly@apple.com>

Export cluster logs on exit

---

test/run.sh

Let's go one version at a time instead of a big jump like in #40 :)

Upgrade kind to v0.6.1

---

test/run.sh

Follows from #42 :)
/cc @JoshVanL

Upgrade kind to v0.7.0

---

test/run.sh

This upgrade previously caused issues with networking... let's see if it works now (and if not, gradually start working our way back to work out what's causing the problems).
Signed-off-by: James Munnelly <jmunnelly@apple.com>

Upgrade kind to v0.11.1

---

SECURITY.md

Branched from #46 
@munnerz 
```release-note
NONE
```

Security.md

---

go.mod
go.sum

Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>
/assign @jakexks 
```release-note
NONE
```

Update csi-lib to v0.1.0

---

.gitignore
Dockerfile
cmd/app/app.go
cmd/main.go
test/e2e/suite/suite_test.go
test/run.sh

Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>
/assign @jakexks

Ensure all names use cert-manager-csi-driver

---

README.md

Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>

Explain incompatibility with self signed issuers

---

Makefile
cmd/app/app.go
deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.yaml

Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>
/assign @irbekrm

Updates tag version to v0.2.0, updates helm README docs

---

README.md

Fix logo location to use specific SHA

---

test/run.sh

Update cert-manager:v1.8.0 in test runner

---

Dockerfile

Bumps alpine version `v3.14` -> `v3.15`

---

SECURITY.md

Updates reference in SECURITY.md to point to `jetstack/cert-manager` -> `cert-manager/cert-manager`

---

deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.yaml

Bumps bump-csi-node-driver-registrar to `v2.5.0`, Bumps livenessprobe to `v2.6.0`

---

Makefile
cmd/app/app.go
deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.yaml

/assign @munnerz 
/hold
until we are ready to release `v0.3.0`

Sets csi-driver version to v0.3.0

---

README.md

Will stealth merge via manually marking with lgtm

Update to smaller logo with correct size

---

deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/templates/daemonset.yaml
deploy/charts/csi-driver/values.yaml

Add optional nodeSelector to helm chart

---

Dockerfile
go.mod
hack/tools/go.mod

Upgrade go to v1.19

---

Makefile
deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.yaml

/hold
Until the other PRs have gone in.

Updates release to v0.4.0, ready for release

---

deploy/charts/csi-driver/Chart.yaml
deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/templates/daemonset.yaml
deploy/charts/csi-driver/templates/serviceaccount.yaml
deploy/charts/csi-driver/values.yaml

Signed-off-by: Sitaram IYER <sitaramkm@gmail.com>
Add support for imagePullSecrets in Helm to pull csi-driver from private repos. Fixes #112

Add support for imagePullSecrets. Fixes #112

---

deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/templates/daemonset.yaml
deploy/charts/csi-driver/values.yaml

Signed-off-by: Cédric Schieli <cschieli@gmail.com>

Add support for non-standard kubelet root directory

---

Dockerfile

Updates alpine in Dockerfile to 3.16.2

---

OWNERS

Copied the owners from https://github.com/cert-manager/cert-manager/blob/master/OWNERS

Update OWNERS file based on cm

---

.github/dependabot.yaml

Add dependabot GH job

---

Makefile

Spotted during the release of v0.6.0 by @wallrj

Fix push command and comment

---

Makefile

Add Make target for creating Helm chart

---

deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.yaml

Updates to csi-driver values file for Venafi docs

MMcL-values-edit

---

deploy/charts/csi-driver/README.md

similar to https://github.com/cert-manager/approver-policy/pull/367

Remove README header since it is already included in the artifacthub sidebar

---

deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/templates/_helpers.tpl
deploy/charts/csi-driver/templates/daemonset.yaml
deploy/charts/csi-driver/values.linter.exceptions
deploy/charts/csi-driver/values.schema.json
deploy/charts/csi-driver/values.yaml
make/00_mod.mk

Enabling these two features that were added in the Helm module:
https://github.com/cert-manager/csi-driver/blob/a4159243f5ad4002afd16f214d7f1028ddfba52c/make/00_mod.mk#L44-L45
I also had to make a few additional changes to fix bugs the linter found.

Enable helm-tool linter and schema generator

---

deploy/charts/csi-driver/templates/clusterrole.yaml
deploy/charts/csi-driver/templates/clusterrolebinding.yaml
deploy/charts/csi-driver/templates/csidriver.yaml
deploy/charts/csi-driver/templates/daemonset.yaml
deploy/charts/csi-driver/templates/serviceaccount.yaml

similar to https://github.com/cert-manager/approver-policy/pull/381

Helm: Use same include statement for labels everywhere

---

.golangci.yaml
cmd/app/options/options.go
pkg/apis/defaults/defaults.go
pkg/apis/validation/validation_test.go
pkg/keystore/pkcs12/pkcs12.go
test/e2e/framework/framework.go
test/e2e/framework/helper/certificaterequest.go
test/e2e/framework/helper/pod.go
test/e2e/framework/log/log.go
test/e2e/framework/testenv.go
test/e2e/suite/cases/annotations.go
test/e2e/suite/cases/fsgroup.go
test/e2e/suite/cases/keyencoding.go
test/e2e/suite/cases/pkcs12.go
test/e2e/suite/cases/renew.go
test/e2e/suite/cases/stress.go
test/e2e/suite/cases/usages.go
test/e2e/suite/cases/util.go
test/e2e/suite/cases/variables.go
test/e2e/util/metadata.go

Reduces the list of ignored linters by fixing the go code.

Fix linters

---

pkg/requestgen/generator.go

I saw this code and it spooked me

Rename variable to make the distinction between uriS and uris clearer

---

deploy/charts/csi-driver/README.md
deploy/charts/csi-driver/values.schema.json
deploy/charts/csi-driver/values.yaml

Signed-off-by: Adam Talbot <adam.talbot@venafi.com>

chore: update csi-node-driver-registrar image
